platform :ios, '10.0'
use_frameworks!

target 'Dusty' do
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  
end

target 'Dusty Widget' do
  
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  
end